---
title: "Generation of the Canadian Clinical Drug Data Set"
author: "Daniel Buijs"
date: "2/6/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(dtplyr)
library(dbplyr)
library(data.table)
library(lubridate)
library(stringr)
library(magrittr)
library(testthat)
library(purrr)
library(tibble)

dpd <- src_postgres(dbname = "dpd",
                    host = "rest.hc.local",
                    port = 5432,
                    user = Sys.getenv("rest_user"),
                    password = Sys.getenv("rest_password"),
                    options = "-c search_path=dpd_20180202")

ccdd <- src_postgres(dbname = "ccdd",
                     host = "rest.hc.local",
                     port = 5432,
                     user = Sys.getenv("rest_user"),
                     password = Sys.getenv("rest_password"))


drug <- tbl(dpd, "drug_product")
ing <- tbl(dpd, "active_ingredient")
comp <- tbl(dpd, "companies")
form <- tbl(dpd, "pharmaceutical_form")
route <- tbl(dpd, "route")
schedule <- tbl(dpd, "schedule")
status <- tbl(dpd, "status")
ther <- tbl(dpd, "therapeutic_class")
packaging <- tbl(dpd, "packaging")

ccdd_tm_reg <- tbl(ccdd, "tm_table")
ccdd_ntp_reg <- tbl(ccdd, "ntp_table")
ccdd_mp_reg <- tbl(ccdd, "mp_table")
ccdd_pseudodins_reg <- tbl(ccdd, "pseudodin_table")
ccdd_ntp_device_reg <- tbl(ccdd, "ntp_devices")
ccdd_ntp_dosage_forms <- tbl(ccdd, "ntp_dosage_forms")
ccdd_ntp_ingredients <- tbl(ccdd, "ntp_ingredients")

for(f in list.files("20180123/")) {ccddname <- str_replace(f, ".csv", "")
                                   assign(ccddname, fread(paste0("20180123/", f)))}

```

## Previous Release of the Canadian Clinical Drug Dataset (CCDD)

The previous release files of the CCDD were pushed to GitHub on January 23, 2018. 

```{r ccdd_summary, results='asis'}
library(knitr)
num_tms <- n_distinct(tm_full_release_20180123$tm_code)
num_ntp <- n_distinct(ntp_full_release_20180123$ntp_code)
num_mps <- n_distinct(mp_full_release_20180123$mp_code)
num_dins <- n_distinct(mp_to_din_or_npn_mapping_20180123$Health_Canada_identifier)
num_pseudodins <- filter(mp_full_release_20180123, str_detect(mp_code, regex("^7"))) %>% nrow()
ccdd_summary <- data.frame(`Number of Concepts` = c(num_tms, num_ntp, num_mps, num_dins, num_pseudodins))
rownames(ccdd_summary) <- c("Therapeutic Moeities (TM)", 
                            "Nonproprietary Therapeutic Products (NTP)",
                            "Manufactured Products (MP)",
                            "Drug Identification Numbers (DIN)",
                            "Pesudodins")
kable(ccdd_summary, row.names = TRUE)
```

## Drug Product Database

The most recent extract of the Drug Product Database was published on February 2, 2018. 

```{r dpd_stats}
dpd_20180202_num_dins <- drug %>% distinct(drug_identification_number) %>% tally()
dpd_20180202_num_marketed_dins <- drug %>% filter(extract == "active") %>% 
                        distinct(drug_identification_number) %>% tally()
dpd_20180202_num_human_marketed_dins <- drug %>% filter(extract == "active", class == "Human") %>%
                        distinct(drug_identification_number) %>% tally()
drug_20180103 <- tbl(dpd, in_schema("dpd_20180103", "drug_product"))
dpd_20180103_num_dins <- drug_20180103 %>% distinct(drug_identification_number) %>% tally()
dpd_20180103_num_marketed_dins <- drug_20180103 %>% filter(extract == "active") %>% 
                        distinct(drug_identification_number) %>% tally()
dpd_20180103_num_human_marketed_dins <- drug_20180103 %>% filter(extract == "active", class == "Human") %>%
                        distinct(drug_identification_number) %>% tally()
dpd_product_changes <- dbGetQuery(dpd$con, "SELECT drug_code, case
when s.drug_code is null then 'New drug_code in dpd_20180202'
when t.drug_code is null then 'Drug_code missing in dpd_20180202'
else 'Data Changed'
end as status
from dpd_20180103.drug_product s 
full outer join dpd_20180202.drug_product t using (drug_code)
where s is distinct from t")
dpd_extract_change <- dpd_product_changes %>% filter(status == "Data Changed") %>% left_join(drug_20180103, copy = TRUE) %>% select(drug_code, jan_extract = extract) %>% left_join(drug, copy = TRUE) %>% select(drug_code, jan_extract, feb_extract = extract) %>% filter(!jan_extract == feb_extract)
dpd_brand_name_change <- dpd_product_changes %>% filter(status == "Data Changed") %>% left_join(drug_20180103, copy = TRUE) %>% select(drug_code, jan_brand = brand_name) %>% left_join(drug, copy = TRUE) %>% select(drug_code, jan_brand, feb_brand = brand_name) %>% filter(!jan_brand == feb_brand)
dpd_descriptor_change <- dpd_product_changes %>% filter(status == "Data Changed") %>% left_join(drug_20180103, copy = TRUE) %>% select(drug_code, jan_des = descriptor) %>% left_join(drug, copy = TRUE) %>% select(drug_code, jan_des, feb_des = descriptor) %>% filter(!jan_des == feb_des)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
